// app/pages/onboarding.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })

const config = useRuntimeConfig()
useUserSession()

type OrgEntry = { id: number, login: string, avatarUrl: string | null, type: string }

const { data, pending } = await useFetch<{
  personal: OrgEntry
  orgs: OrgEntry[]
}>('/api/auth/orgs')

const selected = ref<OrgEntry | null>(null)

watch(
  () => data.value,
  (val) => {
    if (val && !selected.value) {
      selected.value = val.personal
    }
  },
  { immediate: true }
)

function install() {
  if (!selected.value) return
  const appSlug = config.public.githubAppSlug
  const targetType = selected.value.type === 'Organization' ? 'Organization' : 'User'
  const url = `https://github.com/apps/${appSlug}/installations/new?target_id=${selected.value.id}&target_type=${targetType}`
  window.location.href = url
}
</script>

<template>
  <div class="min-h-screen flex items-center justify-center p-6">
    <div class="w-full max-w-lg">
      <div class="flex items-center gap-3 mb-8">
        <div class="flex items-center gap-2">
          <div class="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold">
            1
          </div>
          <span class="text-sm font-medium">Select your organization</span>
        </div>
        <div class="flex-1 h-px" />
        <div class="flex items-center gap-2">
          <div class="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold">
            2
          </div>
          <span class="text-sm">Install Void Shield</span>
        </div>
      </div>

      <div class="border border-neutral-800 rounded-xl p-6">
        <div class="flex items-center justify-center gap-4 mb-6">
          <AppLogo class="h-8" />
          <div class="flex gap-1">
            <div class="w-1.5 h-1.5 rounded-full" />
            <div class="w-1.5 h-1.5 rounded-full" />
            <div class="w-1.5 h-1.5 rounded-full" />
          </div>
          <UIcon
            name="i-simple-icons-github"
            class="size-8"
          />
        </div>

        <h2 class="text-xl font-semibold text-center mb-1">
          Select an organization
        </h2>
        <p class="text-sm text-center mb-6">
          Choose where to install Void Shield
        </p>

        <div
          v-if="pending"
          class="flex justify-center py-8"
        >
          <UIcon
            name="i-lucide-loader-circle"
            class="size-6 animate-spin"
          />
        </div>

        <div
          v-else-if="data"
          class="space-y-2 max-h-72 overflow-y-auto"
        >
          <button
            class="w-full flex items-center gap-3 p-3 rounded-lg border transition-colors text-left"
            :class="
              selected?.login === data.personal.login
                ? 'border-primary bg-primary/10'
                : 'border-neutral-700 hover:border-neutral-500'
            "
            @click="selected = data.personal"
          >
            <img
              :src="data.personal.avatarUrl ?? undefined"
              :alt="data.personal.login"
              class="w-8 h-8 rounded-full"
            >
            <div class="flex-1 min-w-0">
              <p class="text-sm font-medium truncate">
                {{ data.personal.login }}
              </p>
              <p class="text-xs">
                Personal account
              </p>
            </div>
            <div
              class="w-4 h-4 rounded-full border-2 flex-shrink-0"
              :class="
                selected?.login === data.personal.login
                  ? 'border-primary bg-primary'
                  : 'border-neutral-500'
              "
            />
          </button>

          <button
            v-for="org in data.orgs"
            :key="org.id"
            class="w-full flex items-center gap-3 p-3 rounded-lg border transition-colors text-left"
            :class="
              selected?.login === org.login
                ? 'border-primary bg-primary/10'
                : 'border-neutral-700 hover:border-neutral-500'
            "
            @click="selected = org"
          >
            <img
              :src="org.avatarUrl ?? undefined"
              :alt="org.login"
              class="w-8 h-8 rounded-full"
            >
            <div class="flex-1 min-w-0">
              <p class="text-sm font-medium truncate">
                {{ org.login }}
              </p>
              <p class="text-xs">
                Organization
              </p>
            </div>
            <div
              class="w-4 h-4 rounded-full border-2 flex-shrink-0"
              :class="selected?.login === org.login ? 'border-primary bg-primary' : 'border-neutral-500'"
            />
          </button>
        </div>

        <div class="flex items-center justify-between mt-6 pt-4 border-t border-neutral-800">
          <UButton
            to="https://github.com/settings/organizations"
            external
            variant="ghost"
            color="neutral"
            size="sm"
          >
            <UIcon
              name="i-lucide-plus"
              class="size-4"
            />
            Add Organization
          </UButton>

          <UButton
            :disabled="!selected"
            size="sm"
            @click="install"
          >
            Install
            <UIcon
              name="i-lucide-arrow-right"
              class="size-4"
            />
          </UButton>
        </div>
      </div>
    </div>
  </div>
</template>

// app/(dashboard)/onboarding/page.tsx
"use client";

import { ArrowRightIcon, BuildingIcon, UserIcon } from "lucide-react";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { siteConfig } from "@/lib/config";

interface GithubTarget {
  avatarUrl: string;
  id: number;
  login: string;
  type: string;
}

interface OrgsResponse {
  orgs: GithubTarget[];
  personal: GithubTarget;
}

export default function OnboardingPage() {
  const [data, setData] = useState<OrgsResponse | null>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch("/api/github/orgs")
      .then((r) => r.json())
      .then((d: OrgsResponse) => {
        setData(d);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, []);

  function installUrl(id: number, type: string) {
    const targetType = type === "Organization" ? "Organization" : "User";
    return `${siteConfig.links.githubApp}/installations/new?target_id=${id}&target_type=${targetType}`;
  }

  const targets = data ? [data.personal, ...data.orgs] : [];

  return (
    <main className="mx-auto max-w-lg px-6 py-16">
      <h1 className="mb-2 font-semibold text-2xl">Choose an account</h1>
      <p className="mb-8 text-muted-foreground">
        Install {siteConfig.name} on your personal account or an organization to
        start scanning repositories.
      </p>

      {loading ? (
        <div className="space-y-3">
          {[0, 1, 2].map((i) => (
            <div
              className="h-16 animate-pulse rounded-xl border bg-muted"
              key={i}
            />
          ))}
        </div>
      ) : (
        <div className="space-y-3">
          {targets.map((t) => (
            <a
              className="flex items-center gap-4 rounded-xl border bg-card p-4 transition-colors hover:bg-muted/50"
              href={installUrl(t.id, t.type)}
              key={t.id}
              rel="noopener"
              target="_blank"
            >
              <img
                alt={t.login}
                className="size-9 rounded-full"
                src={t.avatarUrl}
              />
              <div className="flex-1">
                <p className="font-medium">{t.login}</p>
                <p className="flex items-center gap-1 text-muted-foreground text-xs">
                  {t.type === "Organization" ? (
                    <BuildingIcon className="size-3" />
                  ) : (
                    <UserIcon className="size-3" />
                  )}
                  {t.type}
                </p>
              </div>
              <ArrowRightIcon className="size-4 text-muted-foreground" />
            </a>
          ))}
        </div>
      )}
    </main>
  );
}
