// app/pages/dashboard.vue
<script setup lang="ts">
definePageMeta({ middleware: 'auth' })

const { user, clear } = useUserSession()
const config = useRuntimeConfig()

const { data: installations } = await useFetch('/api/dashboard/installations')

async function logout() {
  await $fetch('/api/auth/logout', { method: 'POST' })
  await clear()
  await navigateTo('/')
}
</script>

<template>
  <div class="min-h-screen bg-neutral-950">
    <header class="border-b border-neutral-800 px-6 py-4 flex items-center justify-between">
      <AppLogo class="h-7" />
      <div class="flex items-center gap-3">
        <UButton
          :to="`https://github.com/apps/${config.public.githubAppSlug}/installations/new`"
          external
          size="sm"
          variant="outline"
          color="neutral"
        >
          <UIcon
            name="i-lucide-plus"
            class="size-4"
          />
          Add organization
        </UButton>
        <UDropdownMenu
          :items="[
            [{ label: user?.login ?? '', disabled: true }],
            [{ label: 'Sign out', icon: 'i-lucide-log-out', onSelect: logout }]
          ]"
        >
          <img
            :src="user?.avatarUrl ?? undefined"
            :alt="user?.login"
            class="w-8 h-8 rounded-full cursor-pointer ring-2 ring-neutral-700 hover:ring-neutral-500 transition-all"
          >
        </UDropdownMenu>
      </div>
    </header>

    <main class="max-w-4xl mx-auto px-6 py-10">
      <h1 class="text-2xl font-semibold text-white mb-2">
        Dashboard
      </h1>
      <p class="text-neutral-400 mb-8">
        Security scan results across your installed organizations.
      </p>

      <div
        v-if="!installations?.length"
        class="text-center py-20"
      >
        <UIcon
          name="i-lucide-shield-off"
          class="size-12 text-neutral-600 mx-auto mb-4"
        />
        <p class="text-neutral-300 font-medium mb-2">
          No installations yet
        </p>
        <p class="text-sm text-neutral-500 mb-6">
          Install Void Shield on an organization to start scanning.
        </p>
        <UButton
          :to="`https://github.com/apps/${config.public.githubAppSlug}/installations/new`"
          external
        >
          Install Void Shield
        </UButton>
      </div>

      <div
        v-else
        class="grid gap-4"
      >
        <div
          v-for="inst in installations"
          :key="inst.installation_id"
          class="bg-neutral-900 border border-neutral-800 rounded-xl p-5 flex items-center gap-4"
        >
          <div class="w-10 h-10 rounded-full bg-neutral-700 flex items-center justify-center flex-shrink-0">
            <UIcon
              name="i-simple-icons-github"
              class="size-5 text-white"
            />
          </div>
          <div class="flex-1 min-w-0">
            <p class="font-medium text-white">
              {{ inst.account_login }}
            </p>
            <p class="text-sm text-neutral-500">
              {{ inst.account_type }}
            </p>
          </div>
          <UBadge
            color="success"
            variant="subtle"
          >
            Active
          </UBadge>
        </div>
      </div>
    </main>
  </div>
</template>

// app/(dashboard)/dashboard/page.tsx
import { eq } from "drizzle-orm";
import { ShieldOffIcon } from "lucide-react";
import { headers } from "next/headers";
import { Button } from "@/components/ui/button";
import { auth } from "@/lib/auth";
import { siteConfig } from "@/lib/config";
import { db } from "@/lib/db";
import { installation } from "@/lib/db/schema";

export default async function DashboardPage() {
  const session = await auth.api.getSession({ headers: await headers() });
  const installations = await db.query.installation.findMany({
    where: eq(installation.userId, session!.user.id),
    orderBy: (t, { desc }) => [desc(t.createdAt)],
  });

  return (
    <main className="mx-auto max-w-4xl px-6 py-10">
      <h1 className="mb-2 font-semibold text-2xl">Dashboard</h1>
      <p className="mb-8 text-muted-foreground">
        Security scan results across your installed organizations.
      </p>

      {installations.length === 0 ? (
        <div className="py-20 text-center">
          <ShieldOffIcon className="mx-auto mb-4 size-12 text-muted-foreground/40" />
          <p className="mb-1 font-medium">No installations yet</p>
          <p className="mb-6 text-muted-foreground text-sm">
            Install {siteConfig.name} on a GitHub organization to start
            scanning.
          </p>
          <Button asChild>
            <a
              href={`${siteConfig.links.githubApp}/installations/new`}
              rel="noopener"
              target="_blank"
            >
              Install Void Shield
            </a>
          </Button>
        </div>
      ) : (
        <div className="grid gap-3">
          {installations.map((inst) => (
            <div
              className="flex items-center gap-4 rounded-xl border bg-card p-5"
              key={inst.id}
            >
              <div className="flex size-10 flex-shrink-0 items-center justify-center rounded-full bg-muted font-semibold text-sm">
                {inst.accountLogin.slice(0, 1).toUpperCase()}
              </div>
              <div className="min-w-0 flex-1">
                <p className="font-medium">{inst.accountLogin}</p>
                <p className="text-muted-foreground text-sm">
                  {inst.accountType}
                </p>
              </div>
              <span className="rounded-full bg-green-500/10 px-2.5 py-0.5 font-medium text-green-600 text-xs dark:text-green-400">
                Active
              </span>
            </div>
          ))}
        </div>
      )}
    </main>
  );
}
